title: Portfolio Christopher Cremona
description: Portfolio professionnel de Christopher Cremona
theme: jekyll-theme-primer

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

plugins:
  - jekyll-seo-tag
