title: Christopher Cremona
description: Portfolio professionnel – Développeur web
url: https://cremonachristopher.github.io
baseurl: /portfolio


markdown: kramdown


theme: minima


collections:
projects:
output: true
permalink: /projects/:name/

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

plugins:
  - jekyll-seo-tag
