title: Christopher Cremona
description: Portfolio
theme: minima

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

minima:
  social_links:
    - title: "Email"
      icon: envelope
      url: "mailto:christowow130@hotmail.fr"
    - title: "GitHub"
      icon: github
      url: "https://github.com/cremonachristopher"
    - title: "LinkedIn"
      icon: linkedin
      url: "https://www.linkedin.com/in/christopher-cremona-b614b7398/"
