title: Christopher Cremona
description: Portfolio
theme: minima

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

email: christowow130@hotmail.fr
github_username: cremonachristopher
linkedin_username: https://www.linkedin.com/in/christopher-cremona-b614b7398/