title: Portfolio Christopher Cremona
description: Portfolio personnel et professionnel
email: christowow130@hotmail.fr
github_username: cremonachristopher
linkedin_username: christopher-cremona-b614b7398

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md

minima:
  social_links:
    - title: "Envoyer un email"
      icon: envelope
      url: "mailto:christowow130@hotmail.fr"
    - title: "GitHub Profile"
      icon: github
      url: "https://github.com/cremonachristopher"
    - title: "LinkedIn Profile"
      icon: linkedin
      url: "https://www.linkedin.com/in/christopher-cremona-b614b7398/"
